apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: labs-container-workshops
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 1
    workshop:
      defaults:
        reserved: 1
        initial: 0
  workshops:
  - name: lab-container-basics
    expires: 40m
    overtime: 10m
    deadline: 60m
    orphaned: 5m
